language: minimal

git:
  depth: false

dist: xenial

services:
  - docker

before_deploy:
  - chmod -R 777 scripts

deploy:
  - provider: script
    script: bash scripts/build_docker.sh
    skip-cleanup: true
    on:
      all_branches: true