name: Publish docker daily
on:
  schedule:
  - cron: '0 4 * * *'

jobs:
  publish_at_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: change file mode
      run: chmod -R 777 scripts
    - name: build & publish docker
      run: bash scripts/build_docker.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
